enable = true
transitionSpeed = 1.0
nimbleMounting = true
mountingEntityBlocklist = []
nimbleElytra = false
elytraRollScreen = false
elytraRollStrength = 20
elytraTickDelay = 10
frontKeyToggleMode = false
expectedThirdPersonDistance = 4.0
